version: "2"
services:
  php:
    image: php:5.6-alpine
    entrypoint:
      - sh
      - bin/container_php.sh
    volumes:
      - ./:/usr/src/myapp
    working_dir: /usr/src/myapp
    ports:
      - 5001:5001
  node:
    volumes:
      - ./:/usr/src/app
    image: node:7
    working_dir: /usr/src/app
    ports:
      - 8081:80
    entrypoint:
      - sh
      - bin/container_node.sh
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
